### ISSUE TITLE
Query  regarding using of this template

### ISSUE THREAD

**Issue by tanmoysrt** [brunosimon/threejs-template-complex#10]
I am currently building an open source platform where developers can create and manage their portfolio and switch between templates easily.
I like the simplicity of this design.

Can I integrate this in the platform ?
Proper source code link of this github repo and author's name will be mentoned under template .

**Comment by tanmoysrt** [comment]
@brunosimon can you share your thought ?

**Comment by brunosimon** [comment]
No problem with me

**Comment by tanmoysrt** [comment]
@brunosimon Thank you for confirmation !
